name: textmining
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - gensim=3.8.0
  - jupyter=1.0.0
  - matplotlib=3.2.2
  - nltk=3.5
  - pandas=1.1.0
  - pip=20.2.1
  - pyldavis=2.1.2
  - python=3.6.10
  - spacy=2.3.2
  - openpyxl=3.0.4
  - jupyter_contrib_nbextensions=0.5.1
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
    - xlrd==1.2.0
